# Generated by Django 4.2.11 on 2024-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventBanner', models.TextField()),
                ('eventPageURL', models.URLField()),
                ('eventStartDate', models.DateTimeField(blank=True, null=True)),
                ('eventEndDate', models.DateTimeField(blank=True, null=True)),
                ('validStartDate', models.DateTimeField(blank=True, null=True)),
                ('validEndDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='formdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitStartDate', models.DateTimeField()),
                ('visitEndDate', models.DateTimeField()),
                ('noOfGuestAges_10plus', models.IntegerField()),
                ('noOfGuestAges_3to9', models.IntegerField()),
                ('noOfThemeParkDays', models.IntegerField()),
                ('floridaResident', models.BooleanField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
